### ISSUE TITLE
[BUG/ISSUE] f2py fails while building GFIO_ sources if GC_F_* are defined [feature/MAPL_v1.0.0]

### ISSUE THREAD

**Issue by sdeastham** [geoschem/gchp_legacy#29]
In the MAPL v1 feature branch, an error will be thrown while compiling if the environment variable GC_F_INCLUDE (and possibly the other GC_F_* variables) is defined. Specifically, I get the following shortly after the "building "GFIO_" extension" line in the compile log:

error: unknown file type '' (from '[path/to/include/dir]')

(with my include directory, naturally). This is "fixed" if the environment variable is unset, but that will cause issues when compiling GEOS-Chem if the NetCDF include directories are different for NetCDF-Fortran and NetCDF-C. **Note: this error does not appear to be fatal to building GCHP**.

**Comment by lizziel** [comment]
I just pushed an update to this branch to bypass the python install for GMAO_gfio in MAPL. My experience is that this portion of the build is not needed for GCHP, and NASA GMAO confirmed that it should not be needed by anything we would use. GMAO will turn it off by default in a future version of MAPL since very few of their internal users need it.

I will wait to get confirmation from you that the new branch resolves this for you before closing this issue.

**Comment by lizziel** [comment]
This issue is resolved by the following commits:
https://github.com/geoschem/gchp/commit/862bd7acf600fa42b0d4756b284307a901b346bb
https://github.com/geoschem/gchp/commit/e31d6568e5180809742f03f21c39962c9b353a22
