### ISSUE TITLE
[BUG/ISSUE] Duration in HISTORY.rc ignored in dev/12.5.0; files written at duration = frequency

### ISSUE THREAD

**Issue by TerribleNews** [geoschem/gchp_legacy#31]
I am having trouble getting the output I would like with the frequency and duration settings in HISTORY.rc (set through runConfig.sh). I interpret the wiki documentation as saying that files are supposed to be written out every [duration], with data for every [frequency], so each file would have a time dimension of [duration]/[frequency]. Instead, what I'm finding with dev branch 12.5.0, is that it writes files at [frequency] and seems to ignore duration.

**Comment by lizziel** [comment]
The GCHP documentation is for the latest public release and so does not reflect 12.5.0 which is in development. I've updated this issue name to be more targeted to the problematic behavior rather than the doc. Please note there are actually quite a lot of updates that will need to be added to the documentation for the 12.5 release. I do not recommend using that version yet unless you are beta testing only.

That being said, this behavior is unexpected and either a bug in the new version of MAPL or a change in MAPL config file behavior that GMAO did not alert us about. Thanks for bringing this to our attention! I will post updates here on status.

**Comment by lizziel** [comment]
I am able to reproduce this issue in versions of GCHP prior to 12.5.0 as well. I reported it to GMAO and they are not able to reproduce it on their end in GEOS. However, they are using a more recent version of MAPL. We will be updating MAPL again soon. If the issue persists after the update then I will dive deeper into this issue. See also https://github.com/GEOS-ESM/MAPL/issues/21.

The GCHP online documentation is now updated to specify a limit of one timestamp per output diagnostic file.

**Comment by TerribleNews** [comment]
Thanks! A workaround I have been able to use is to set the filename template to only include the day, not the hour, then each hours' output is appended to that file. It's not very flexible, but can help avoid proliferation of files. Also, it seems if you do that, the duration is used to determine how many times to write to the file, so for example, I have
template: "%y4%m2%d2.nc4"
frequency: 010000
duration: 240000
and if I set duration to, say, 060000 only the first 6 hours of each day would be output.

**Comment by lizziel** [comment]
Interesting. This sheds a bit more light on the issue. Thanks!

**Comment by lizziel** [comment]
This issue goes away in a newer version of MAPL I am testing (https://github.com/GEOS-ESM/MAPL/commit/9453677868678e81da779bf3b0b083f61848a77e). The updated version will not be put into [GCHP](https://github.com/geoschem/gchp) but will be in [gchp_ctm](https://github.com/geoschem/gchp_ctm), the new GCHP repository currently in development. That repository will be released as GCHP 13.0.0, at which point the legacy GCHP repository will be retired.
