### ISSUE TITLE
[BUG/ISSUE] There doesn't seem to be a way to turn on traditional debug printing

### ISSUE THREAD

**Issue by TerribleNews** [geoschem/gchp_legacy#43]
The GCHP wiki says "Change "ND70" in input.geos from 0 to 1 to turn on extra GEOS-Chem print statements in the main log file. " but I tried adding a Diagnostics menu to my input.geos and it just gets ignored. Is there a way to get the LPRT flag set to true without recompiling?

**Comment by yantosca** [comment]
I think the issue is that the ND70 switch is only activated when BPCH_DIAG=y, which is obviously not the case for GCHP.

What you could do for now is to manually set Input_Opt%ND70 =1 in routine Set_Input_Opt_Mod and that will force debug printout.  Caution!  There might be a few places in the code where print statements are not trapped by "am_I_Root".  We are fixing those in 12.6.0.

We are currently taking out the bpch code from 12.7.0 (at least most of it) so this should be less of an issue going forward.

**Comment by msulprizio** [comment]
This has been added as a feature request on the GCC repository. See https://github.com/geoschem/geos-chem/issues/73.

**Comment by yantosca** [comment]
This issue will be corrected in GEOS-Chem 12.7.0.  We have moved the debug printout switch to the SIMUATION MENU, which is always read.  See https://github.com/geoschem/geos-chem-unittest/commit/7a1772223c17b506a9f2bc14a29a3e2cd599c415.  We will make the same update in the GCHP repo as well.

**Comment by lizziel** [comment]
This update is in 12.7.0.
