### ISSUE TITLE
[QUESTION]Should it make cleanup_output everytime at the beginging of smulation?

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/gchp_legacy#60]
Hi @lizziel @yantosca 
I use the v12.6.0 and find that the model will cut off sometimes at any module resolution.
And if I make cleanup_output at the beginning of the simulation, it will improve.
I wonder whether the cleanup_output will effect the simulation, and should I make cleanup_output everytime?

**Comment by lizziel** [comment]
Hi @hongjianweng,

What error are you running into when you do not do make cleanup_output? Please provide your log files so that I can check if the errors associated with not doing make cleanup_output are what you are seeing.

You should always do make cleanup_output prior to reusing a run directory for a single run. By single run I mean not consecutive runs reusing a previously generated restart file. If you would like to keep the output, config, and log files of a previous run you can archive them using the archiveRun.sh tool provided in the run directory prior to doing make cleanup_output. This will put all of the files into a subdirectory in the run directory that will not be deleted during cleanup.

For information about why make cleanup_output is important, see the [Running GCHP: Basics wiki page, section Rerunning Without Cleaning](http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Basics#Rerunning_Without_Cleaning). 

For instructions on how to archive a run, see the [Running GCHP: Basics wiki page, section Archiving a Run](http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Basics#Archiving_a_Run).

**Comment by hongjianweng** [comment]
[HEMCO.log](https://github.com/geoschem/gchp/files/4028796/HEMCO.log)
[gchp.log](https://github.com/geoschem/gchp/files/4028797/gchp.log)
[compile.log](https://github.com/geoschem/gchp/files/4028798/compile.log)
[slurm-23055.log](https://github.com/geoschem/gchp/files/4028800/slurm-23055.log)
These are the log files, please check!

**Comment by lizziel** [comment]
Hi @hongjianweng 
The errors you see do not look like anything I have seen related to not cleaning up the run directory. Are you still running into this error? Is it consistently there if you do not clean the run directory? Is it consistently gone if you do clean the run directory? If it is random and sporadic I wonder if it is a system error.

**Comment by lizziel** [comment]
@hongjianweng Can you give an update on the status of this issue?
