### ISSUE TITLE
[BUG/ISSUE]Invoking MPI_ABORT causes Open MPI to kill all MPI processes when run GCHP at c360

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/gchp_legacy#66]
When we run GCHP at c360 using v12.7.2, I will always suddenly kill at
 ****
ParseTimeUnits: Assuming a starting time of 00z
 ParseTimeUnits: Assuming a starting time of 00z
 ParseTimeUnits: Assuming a starting time of 00z
 ParseTimeUnits: Assuming a starting time of 00z
===> Run ended at Fri Apr 3 13:36:42 CST 2020_
****
And the output information shows that:
--------------------------------------------------------------------------
   MPI_ABORT was invoked on rank 344 in communicator MPI_COMM_WORLD
   with errorcode -1719113856.
  
   NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
   You may or may not see output from other processes, depending on
   exactly when Open MPI kills them.
  --------------------------------------------------------------------------
It seems to be a MPI problem.

[Uploading setting and log files.zip…]()

**Comment by lizziel** [comment]
Hi Hongjian,

The issue appears to be occurring during input in ExtData. The standard error out file contains this:
```

pe=00312 FAIL at line=02311    MAPL_ExtDataGridCompMod.F90              <needs informative message>
pe=00312 FAIL at line=01027    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00312 FAIL at line=01728    MAPL_Generic.F90                         <needs informative message>
pe=00312 FAIL at line=00700    MAPL_CapGridComp.F90                     <status=1>
pe=00312 FAIL at line=00558    MAPL_CapGridComp.F90                     <status=1>
pe=00312 FAIL at line=00827    MAPL_CapGridComp.F90                     <status=1>
pe=00312 FAIL at line=00387    MAPL_Cap.F90                             <status=1>
pe=00312 FAIL at line=00268    MAPL_Cap.F90                             <status=1>
pe=00312 FAIL at line=00179    MAPL_Cap.F90                             <status=1>
pe=00312 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
pe=00312 FAIL at line=00028    GEOSChem.F90                             <status=1>
```

Try turning on the MAPL debug flag in file runConfig.sh. This will print out more information during the input stage and should give a clue on if it is failing on a certain file. 

Were you successfully able to the run your same setup at lower resolution? According to your log file you are running at c180, not c360. Is that intentional? Check your resolution in runConfig.sh to make sure you are running at the resolution you think you are. Try running at lower resolution to isolate if the issue is specific to c180 or above.

Lastly, how many cores per node do you have available? I see you are using 60 cores/node which is a lot. You haven't already you may hit a memory per core limit. After determining if you have an input file issue by using the MAPL debug flag, you can also up your memory per core by using more nodes and fewer cores per node, but still reserving full memory per node.

Let me know if any of this helps. I am particularly interested in what you see when turning on ExtData debug since I strongly suspect this is an input file issue.

**Comment by hongjianweng** [comment]
Hi Lizzie,

Thanks for your advice, and turning on ExtData debug really works. Follow your advice, I turn on the MAPL debug flag, and find that the above issue is because of the lack of some files when the version updates to 12.7.2. I download the lack data and the above issue did not appear, I can successfully run at low resolution including c24 and c48.

But unfortunately there are new problems when I run c360 or c180.
There are the issue for c360:
[gchp.txt.log](https://github.com/geoschem/gchp/files/4431506/gchp.txt.log)
[gchp.run.e82058.txt](https://github.com/geoschem/gchp/files/4431508/gchp.run.e82058.txt)

And there are the setting for c360:
[gchp.run.txt](https://github.com/geoschem/gchp/files/4431507/gchp.run.txt)
[runConfig.sh.txt](https://github.com/geoschem/gchp/files/4431509/runConfig.sh.txt)

For our server, there are 64 cores and 256GB memory per node. I try total cores from 900 to 1800 for c360. I also up my memory per core by using more nodes and fewer cores per node, reserving full memory per node. But it is still wrong for c360 or c180. So, should I up core number or there are other cause.

Thank you for your attention and look for your replies!

**Comment by hongjianweng** [comment]
<img width="630" alt="微信截图_20200404222159" src="https://user-images.githubusercontent.com/31821522/78453204-bde73280-76c2-11ea-9727-c288d4d874e8.png">
I  found that image about the new issue upload failed and upload again!

**Comment by lizziel** [comment]
Hi Hongjian,
This appears to be an MPI issue which has to do with your libraries and/or system. I searched the internet for your error message and these came up:

- https://bugzilla.redhat.com/show_bug.cgi?id=1747517
- https://github.com/openucx/ucx/issues/3130

Do you have a systems administrator where you are who installed MPI on your cluster? You may need to fiddle with the MPI settings. I am also bringing @sdeastham in on this since he was recently looking at MPI UCX and may have resources to share.

**Comment by sdeastham** [comment]
Following up on those:

* Do you know if all the nodes are using the same Infiniband hardware? There is some suggestion that this can happen if using "mixed hardware" configurations (and there may be some ways to fix this, either by restricting your hardware choice or - if there are multiple Infiniband interfaces - restricting them through command line options)
* Do you know what version of UCX is in use? the command "ucx_info" may help (after loading your environment)
*  As @lizziel mentioned, it may be worth setting some of the OpenMPI settings as described by those bug reports.

Unfortunately when things go wrong deep in MPI it's a nightmare to diagnose - but I agree with @lizziel that this is likely to be something system-level.

**Comment by hongjianweng** [comment]
Hi lizziel,  Sebastian:

Thanks for your advices.
Yes, we use "mixed hardware" configurations, and we have asked the systems administrator to provide  same Infiniband hardware system, which takes time to reset environment. I will tell you on the progress.
Our UCX is version 1.6.0, which I think is new enough.

**Comment by hongjianweng** [comment]
Hi lizziel, Sebastian:

I have successfully run at c180 and c360 with the same InfiniBand hardware system.
Thanks again for your attention and suggestions. 
In general, turning on MAPL Debug is really helpful. 

Our environment finally shows that:
netcdf/4.4.1-parallel
mpi/openmpi/3.1.3
intel/18.0.2
We use 10 nodes and 60 cores per node for c180, and 20 nodes and 45 cores per node for c360.
I hope the information above is helpful for those who would like to run high resolution.

**Comment by sdeastham** [comment]
Hi Hongjiang,

Fantastic! Best of luck in your future GCHP usage!

@lizziel I guess we should add something about this to the wiki? From what I understand it’s not uncommon for MPI to react poorly to mixed Infiniband hardware. I don’t really think of it as a “Known Issue” so I’m not quite sure where it should go on the wiki – maybe somewhere in the GCHP setup pages?

**Comment by lizziel** [comment]
That's great news! I added the mixed hardware warning to the [GCHP wiki entry for Hardware Requirements](http://wiki.seas.harvard.edu/geos-chem/index.php/GCHP_Hardware_and_Software_Requirements#Hardware_Requirements). I also tagged this issue MPI which I would like to do moving forward with all MPI-related issues. This will help isolate the history of all MPI issues encountered.
