### ISSUE TITLE
[BUG/ISSUE] compiling GCHP 12.8.2

### ISSUE THREAD

**Issue by davidyung-GitHub** [geoschem/gchp_legacy#68]
Dear support team,

Please shed some light on this issue, GCHP 12.3.2 did run successfully in the same cluster.
Here are the logs: 
[GCHP_compile.slurm.txt](https://github.com/geoschem/gchp/files/4715521/GCHP_compile.slurm.txt)
[gchp.env.txt](https://github.com/geoschem/gchp/files/4715522/gchp.env.txt)
[compile.log](https://github.com/geoschem/gchp/files/4715515/compile.log)

Many thanks,
David

**Comment by lizziel** [comment]
Hi David,
Did you previously build and run GCHP with the same environment? Your build is failing in MAPL, but MAPL has not changed for quite a while. It never actually gets to building GCHP. The first error in compile.log (found by following instructions [here](http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_GCHP#Compilation_Tips)) is this:

`pfio_base.F90(6): error #7013: This module file was not generated by any release of this compiler.   [MPI]`

Did you clean your source code before building (make clean_all)? If not, I wonder if you previously built with a different set of libraries. Alternatively, you may be using an MPI library not built with your compiler. If you have system administrators who work on your compute cluster, check with them that the libraries you are loading are compatible, e.g. your MPI is built with ifort18.

**Comment by davidyung-GitHub** [comment]
Hi Lizzie,
I see what I missed in the log. Thanks for your help, I did clean the source code beforehand. I will talk to our system administrators.

**Comment by joeylamcy** [comment]
Hi Lizzie, 

Our last successful build is version 12.3.2 (although I somehow cannot replicate that), but in that version, there is no folder called GMAO_pFIO. Many files in GMAO_pFIO contains a line "use mpi". That may explain why our build fails. 

Best, 
Joey

**Comment by lizziel** [comment]
Hi Joey, 12.5.0 featured a newer MAPL library from GMAO, including GMAO_pFIO for parallel file I/O. Previously MAPL gets MPI library definitions by including header files, e.g. include "mpif.h". This use of MPI in fortran is slated for deprecation and the standard now recommends USE MPI instead. It is therefore used throughout the newer library. 

I checked the 12.3.2 code and use mpi is there in a few places, though only a few. Specifically it is GFDL_fms which is required for building the advection component fvdycore. It is curious that you are no longer able to build that version when you used to be able to. Feel free to post your compile log here if you want another set of eyes on it.

**Comment by joeylamcy** [comment]
version 12.3.2 is compiled succesfully on our cluster with openmpi 3.1.0 and ifort 18.0 ([compile_12.3.2_openmpi_ifort18.log](https://github.com/geoschem/gchp/files/4798781/compile_12.3.2_openmpi_ifort18.log)), but version 12.8.2 fails using the same mpi and compilers. ([compile_12.8.2_openmpi_ifort18.log](https://github.com/geoschem/gchp/files/4798777/compile_12.8.2_openmpi_ifort18.log))

**Comment by lizziel** [comment]
@joeylamcy , you are still getting the same error as before so I suspect this is an incompatibility with your specific library version combination and the newer version of MAPL that came in with 12.5.0. 
```
Throw.F90(48): error #7013: This module file was not generated by any release of this compiler.   [MPI]
      use MPI
----------^
```

One thing I notice is your Intel compiler path is this: `/opt/share/intel/2018u2/compilers_and_libraries_2018.2.199`
However, 2018.2.199 is the version number of Intel MPI and not an Intel compiler. What version of the Intel compiler are you using?

Given that 2018.2.199 is in your path, I suspect you have Intel MPI. You could try building with that instead of OpenMPI 3.1.1.

You should also check with your system administrator on what other compilers and MPI are available, and if they can build you a custom set. For reference I can successfully compile the following compiler and MPI combinations for GCHP 12.8.2:
Intel 17.0.4 + OpenMPI 3.1.1
Intel 18.0.5 + OpenMPI 4.0.1
Intel 19.0.5 + OpenMPI 4.0.1
GCC 8.2.0 + OpenMPI 3.1.1

Intel compilers require a license but GCC and OpenMPI are both free to download.

**Comment by joeylamcy** [comment]
Thank you for your suggestion. I tried compiling with intel MPI with some modifications to the makefile headers (#71 ) and the compilation is successful.

Apart from changing the makefile headers and soft-linking mpifort to mpiifort, I also have to manually append the path of mpi.h to CPATH, but I assume this is specific to the installation of intel MPI on our cluster.

Btw, the last section in [Setting Up the GCHP Environment](http://wiki.seas.harvard.edu/geos-chem/index.php/Setting_Up_the_GCHP_Environment) seems outdated. The ESMA_base.mk no longer contains any lines of `ESMF_COMM`.

**Comment by lizziel** [comment]
I'm very glad Intel MPI worked for you. Starting with GCHP 13.0.0 we will be doing regular testing with Intel MPI as well as OpenMPI using a continuous integration pipeline on Azure. The testing will also include multiple compilers. Moving forward, the history of testing per version will be transparent on GitHub which should help users hone in on what compiler and MPI combination and versions are most likely to work.

Also starting in version 13.0.0, the GNU build system will be retired and replaced with CMake. The makefile modifications you had to make for GCHP 12.8.2 with Intel MPI will no longer be necessary with that release. Your path issues may also be cleared up since CMake will auto-generate makefiles based on your system rather than rely on hard-coded Makefiles that have proven to be brittle.

Thank you for your feedback on the wiki. I just updated the page on setting up the GCHP environment to remove the guidance for source code changes necessary for Intel MPI. Those were indeed outdated and no longer necessary. I also expanded the MPI section of [Hardware and Software Requirements](http://wiki.seas.harvard.edu/geos-chem/index.php/GCHP_Hardware_and_Software_Requirements) to link to your makefile header modifications needed for Intel MPI. Thank you very much for putting that on GitHub. Finally, I updated the wiki to give a heads up on each page of that manual that the documentation will be edited over the coming months for GCHP 13.0.0. That release will be a major version update and users will need to pay close attention to changes in the documentation when getting started with the release.
