### ISSUE TITLE
[QUESTION] Why does GCHP fail when meteorology turned on in 12.9.3 HEMCO_Config.rc

### ISSUE THREAD

**Issue by aechristiansen** [geoschem/gchp_legacy#73]
I am running GCHP 12.9.3 at c180. The model runs successfully when I turn the master switch for meteorology off. However, when I switch this to "true" and change nothing else, I encounter the following error when reading the HEMCO config file:

```
2D import error: CONV_DEPTH
HCO_SetServices (HCOI_ESMF_MOD.F90)            212
```

And my slurm output shows this:

```
Currently Loaded Modules:
  1) git/2.17.0-fasrc01      5) szip/2.1-fasrc03
  2) intel/18.0.5-fasrc01    6) hdf5/1.10.5-fasrc02
  3) openmpi/4.0.1-fasrc01   7) netcdf/4.7.1-fasrc01
  4) zlib/1.2.11-fasrc02     8) netcdf-fortran/4.5.2-fasrc01

 

pe=00003 FAIL at line=00265    MAPL_VarSpecMod.F90                      <status=-1>
pe=00003 FAIL at line=02874    MAPL_Generic.F90                         <status=-1>
pe=00004 FAIL at line=00265    MAPL_VarSpecMod.F90                      <status=-1>
pe=00004 FAIL at line=02874    MAPL_Generic.F90                         <status=-1>
pe=00004 FAIL at line=01720    Chem_GridCompMod.F90                     <status=-1>
pe=00003 FAIL at line=01720    Chem_GridCompMod.F90                     <status=-1>
pe=00012 FAIL at line=00265    MAPL_VarSpecMod.F90                      <status=-1>
pe=00012 FAIL at line=02874    MAPL_Generic.F90                         <status=-1>
```

I have attached the full gchp log. Thanks!
[gchp_mettest.log.txt](https://github.com/geoschem/gchp/files/5105128/gchp_mettest.log.txt)

**Comment by lizziel** [comment]
Hi @aechristiansen,

GCHP does not get read information about general meteorology from HEMCO_Config.rc and so it should always be set to false. The information about meteorology comes instead from config file ExtData.rc. That file specifies file location and read information to accompany the fields turned on in HEMCO_Config.rc, as well as for fields that are defined in source code file Chem_Registry.rc. For meteorology, the fields are declared in the latter. The accompanying path and read frequency/regridding information are in ExtData.rc.

A little bit more background: Unlike GEOS-Chem Classic, the file paths and interpolation information in HEMCO_Config.rc are not read at all in GCHP. Those columns are generally ignored. A discrepancy between what is turned on in HEMCO_Config.rc and what is included in ExtData.rc can result in errors.

Is there a reason you are turning meteorology in HEMCO_Config.rc on? Let me know what you are trying to do and I can help you figure out what needs to change.

**Comment by aechristiansen** [comment]
Ah I see, thanks, @lizziel. I think my problem came from a misunderstanding of how GCHP is different from GEOS-Chem Classic. I didn't realize that the file paths in HEMCO_Config file were not being read in -- I had thought that because met was set to false in HEMCO, it was not being used. I only wanted to make sure it was included!

To clarify, is HEMCO_Config.rc still used to turn inventories on and off, or is that also in ExtData.rc now?

**Comment by lizziel** [comment]
Yes, HEMCO is still used to turn on/off emissions inventories. Everything that is set to true in the HEMCO_Config.rc file that comes with GCHP run directories is used in the default GCHP run. This includes the HEMCO extensions as well. The parts that are ignored are in the individual emissions entries. Here is an example that shows the parts that are ignored by GCHP in bold:

0 NEI11_SURFACE_NO     ***$ROOT/NEI2011/v2015-03/$MM/NEI11_0.1x0.1_2011$MM$DD.nc          NO       2006-2013/1-12/1-31/* C xy  kg/m2/s***  NO   251/1007     1 50

For this case, if NEI11 is turned on at the top of the file, GCHP will try to match the variable name here in the second column with the entry for it in ExtData.rc. Definitely open up that file and find it to get familiar with the information there. A guide to the entries in that file is at the very top in the header. Note also that the masking, scaling, and hierarchy (show in the last three columns in HEMCO_Config.rc) are still used in GCHP. It is only the I/O portion of HEMCO_Config.rc that is ignored. Once input using the information in ExtData.rc, HEMCO still applies the masking and scaling to the values.

There is one notable exception to all of this. If the emission entry in HEMCO_Config.rc has dashes for filename etc, then GCHP will not look for that file in ExtData.rc. The dashes means the variable is not coming from its own input file (true for GC-Classic as well), and just like in GC-Classic, HEMCO will use the last entry above it that does have a filename to set the values. This is true for GCHP as well. The file info will not be searched for in ExtData.rc

It is not at all obvious right now that GCHP ignores some of HEMCO_Config.rc. We are planning an update over the next year or so to split out the file I/O portion of HEMCO from HEMCO_Config.rc so that there are two separate files. This way models that skip HEMCO I/O (such as GCHP) would not have that superfluous information in the run directory and users would not get confused by its presence.

I hope this helps!

**Comment by aechristiansen** [comment]
Thank you for that explanation! This was very helpful.
